services:
  llamacpp-devstral:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - /home/laineh/models:/models
    command: --model /models/Devstral-Small-2-24B-Q4_K_M/mistralai_Devstral-Small-2-24B-Instruct-2512-Q4_K_M.gguf
            --alias devstral
            --host 0.0.0.0
            --port 8080
            --no-webui
            --n-cpu-moe 36
            --flash-attn on
            --temp 1.0
            --top-p 1.0
            --top-k 0
            --n-gpu-layers 30


    networks:
      - lalamos-net
