name: sheska-llm
services:
  openwebui:
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:main-slim
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    networks:
      - lalamos-net
      - scrape-net
# FIRECRAWL
  firecrawl-db:
    restart: unless-stopped
    image: nuq-postgress
    build:
      ./external/firecrawl/apps/nuq-postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    networks:
      - scrape-net
    hostname: firecrawl-db
    volumes:
      - nuq-data:/var/lib/postgresql/data
  firecrawl-redis:
    restart: unless-stopped
    image: sheska-llm/redis
    build:
      context: ./external/firecrawl/apps/redis
      args:
        REDIS_VERSION: latest
    networks:
      - scrape-net
    hostname: firecrawl-redis
    volumes:
      - redis_server:/data:rw
    user: root
  firecrawl-api:
    restart: unless-stopped
    image: sheska-llm/firecrawl-api
    build:
      context: ./external/firecrawl/apps/api
    ports:
      - "3002:3002"
    networks:
      - scrape-net
    volumes:
      - type: bind
        source: ./external/firecrawl/apps/api/.env
        target: /app/.env
# LLAMA.CPP SERVER
  llamacpp-multi-model:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - /home/laineh/models:/models
      - ./llamacpp.config.ini:/config.ini
    command: --models-preset /config.ini
            --host 0.0.0.0
            --port 8080
            --threads 28
            --models-max 1
    ulimits:
      memlock: -1
    networks:
      - lalamos-net
volumes:
  open-webui:
  nuq-data:
  redis_server:

networks:
  lalamos-net:
  scrape-net:
